apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "template.example.com"
spec:
  type: Mutating
  operations: ["CREATE", "UPDATE"]
  resources: ["clusters"]
  apiGroups: ["provisioning.cattle.io"]
  objectSelector:               
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  javascript: |
    const secretName = request.object.spec.cloudCredentialSecretName;
    const secretObject = get("Secret", "v1", secretName.replace(':', '/'));
    let cngValue = request.object.spec.rkeConfig.additionalManifest;
    let key_name = "";
    Object.keys(secretObject.data).forEach(function(key, index) {
      key_name = key.split('-').slice(1).join('-'); # remove first string before '-'
      key_name = key_name.replaceAll('-', '_').toUpperCase(); # replace all '-' to '_' and uppercase
      cngValue = cngValue.replaceAll('REPLACE_TOKEN_TO_CLOUD_CREDENTIAL_' + key_name, secretObject.data[key]);
    });
    request.object.spec.rkeConfig.additionalManifest = cngValue;
    mutate(request.object);
