apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: delete.autoscaler.helmchart
spec:
  operations: ["DELETE"]
  resources: ["clusters"]
  apiGroups: ["cluster.x-k8s.io"]
  javascript: |
    const cl = request.name;
    const namespace = request.namespace;
    const HelmChart = get("HelmChart", "helm.cattle.io/v1", namespace + "/" + cl + "-autoscaler");
    if (HelmChart) {
      const result = remove(HelmChart);
    }